SQLALCHEMY_DATABASE_URI = 'postgresql://postgres:postgres@0.0.0.0:5432'
SECRET_KEY = 'aSup3rS33kret'
DEBUG_TB_INTERCEPT_REDIRECTS = False
DEBUG_TB_PROFILER_ENABLED = True
SQLALCHEMY_TRACK_MODIFICATIONS = False
